In [721]:
import pandas as pd

In [722]:
malaria = pd.read_csv("../data/malaria_raw.csv")

In [723]:
malaria.head()

,Unnamed: 0,period,year,month,county,code,cases_under_5yo,cases_over_5yo,total_cases,temp,rainfall,month_code,county_code
0,0,22-Jan,2022,Jan,Baringo,KE_County_30,663,1975,2638,18,96.54,1,30
1,1,22-Feb,2022,Feb,Baringo,KE_County_30,805,1759,2564,19,45.28,2,30
2,2,22-Mar,2022,Mar,Baringo,KE_County_30,762,1370,2132,20,77.64,3,30
3,3,22-Apr,2022,Apr,Baringo,KE_County_30,597,1146,1743,19,261.67,4,30
4,4,22-May,2022,May,Baringo,KE_County_30,725,1700,2425,17,169.35,5,30

In [724]:
malaria.tail()

,Unnamed: 0,period,year,month,county,code,cases_under_5yo,cases_over_5yo,total_cases,temp,rainfall,month_code,county_code
1687,1687,24-Aug,2024,Aug,West Pokot,KE_County_24,2674,6152,8826,16,221.69,8,24
1688,1688,24-Sep,2024,Sep,West Pokot,KE_County_24,2018,4622,6640,17,172.77,9,24
1689,1689,24-Oct,2024,Oct,West Pokot,KE_County_24,1987,4859,6846,19,14.81,10,24
1690,1690,24-Nov,2024,Nov,West Pokot,KE_County_24,1992,4850,6842,18,154.62,11,24
1691,1691,24-Dec,2024,Dec,West Pokot,KE_County_24,1313,2335,3648,18,8.58,12,24

In [725]:
malaria.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1692 entries, 0 to 1691
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       1692 non-null   int64
 1   period           1692 non-null   object
 2   year             1692 non-null   int64
 3   month            1692 non-null   object
 4   county           1692 non-null   object
 5   code             1692 non-null   object
 6   cases_under_5yo  1692 non-null   int64
 7   cases_over_5yo   1692 non-null   int64
 8   total_cases      1692 non-null   int64
 9   temp             1692 non-null   int64
 10  rainfall         1692 non-null   float64
 11  month_code       1692 non-null   int64
 12  county_code      1692 non-null   int64
dtypes: float64(1), int64(8), object(4)
memory usage: 172.0+ KB

In [726]:
malaria.describe()

,Unnamed: 0,year,cases_under_5yo,cases_over_5yo,total_cases,temp,rainfall,month_code,county_code
count,1692.000000,1692.000000,1692.00000,1692.000000,1692.000000,1692.000000,1692.000000,1692.000000,1692.00000
mean,845.500000,2023.000000,1589.33156,5680.725177,7270.056738,20.606383,112.583505,6.500000,24.00000
std,488.582644,0.816738,3136.03515,11314.806775,14392.971601,4.032383,115.512939,3.453073,13.56867
min,0.000000,2022.000000,0.00000,2.000000,3.000000,6.000000,0.000000,1.000000,1.00000
25%,422.750000,2022.000000,18.00000,87.000000,106.500000,18.000000,21.775000,3.750000,12.00000
50%,845.500000,2023.000000,154.00000,580.500000,762.500000,20.000000,74.080000,6.500000,24.00000
75%,1268.250000,2024.000000,1055.00000,4134.750000,5153.750000,22.000000,167.200000,9.250000,36.00000
max,1691.000000,2024.000000,22961.00000,81891.000000,104852.000000,32.000000,607.850000,12.000000,47.00000

In [727]:
malaria = malaria.rename(columns={"Confirmed Malaria (only Positive cases) <5 yrs" : "Cases(<5 yrs)"})

In [728]:
malaria.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1692 entries, 0 to 1691
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       1692 non-null   int64
 1   period           1692 non-null   object
 2   year             1692 non-null   int64
 3   month            1692 non-null   object
 4   county           1692 non-null   object
 5   code             1692 non-null   object
 6   cases_under_5yo  1692 non-null   int64
 7   cases_over_5yo   1692 non-null   int64
 8   total_cases      1692 non-null   int64
 9   temp             1692 non-null   int64
 10  rainfall         1692 non-null   float64
 11  month_code       1692 non-null   int64
 12  county_code      1692 non-null   int64
dtypes: float64(1), int64(8), object(4)
memory usage: 172.0+ KB

In [729]:
malaria = malaria.rename(columns={"Confirmed Malaria (only Positive cases) >5 yrs" : "Cases(>5 yrs)"})

In [730]:
malaria.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1692 entries, 0 to 1691
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       1692 non-null   int64
 1   period           1692 non-null   object
 2   year             1692 non-null   int64
 3   month            1692 non-null   object
 4   county           1692 non-null   object
 5   code             1692 non-null   object
 6   cases_under_5yo  1692 non-null   int64
 7   cases_over_5yo   1692 non-null   int64
 8   total_cases      1692 non-null   int64
 9   temp             1692 non-null   int64
 10  rainfall         1692 non-null   float64
 11  month_code       1692 non-null   int64
 12  county_code      1692 non-null   int64
dtypes: float64(1), int64(8), object(4)
memory usage: 172.0+ KB

In [731]:
malaria = malaria.rename(columns={"Confirmed Malaria Cases" : "total_cases"})

In [732]:
malaria.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1692 entries, 0 to 1691
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       1692 non-null   int64
 1   period           1692 non-null   object
 2   year             1692 non-null   int64
 3   month            1692 non-null   object
 4   county           1692 non-null   object
 5   code             1692 non-null   object
 6   cases_under_5yo  1692 non-null   int64
 7   cases_over_5yo   1692 non-null   int64
 8   total_cases      1692 non-null   int64
 9   temp             1692 non-null   int64
 10  rainfall         1692 non-null   float64
 11  month_code       1692 non-null   int64
 12  county_code      1692 non-null   int64
dtypes: float64(1), int64(8), object(4)
memory usage: 172.0+ KB

In [733]:
missing_values = malaria.loc[malaria.isnull().any(axis=1)]

In [734]:
missing_values.head()

Empty DataFrame
Columns: [Unnamed: 0, period, year, month, county, code, cases_under_5yo, cases_over_5yo, total_cases, temp, rainfall, month_code, county_code]
Index: []

In [735]:
missing_values

Empty DataFrame
Columns: [Unnamed: 0, period, year, month, county, code, cases_under_5yo, cases_over_5yo, total_cases, temp, rainfall, month_code, county_code]
Index: []

In [736]:
missing_values.info()

<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       0 non-null      int64
 1   period           0 non-null      object
 2   year             0 non-null      int64
 3   month            0 non-null      object
 4   county           0 non-null      object
 5   code             0 non-null      object
 6   cases_under_5yo  0 non-null      int64
 7   cases_over_5yo   0 non-null      int64
 8   total_cases      0 non-null      int64
 9   temp             0 non-null      int64
 10  rainfall         0 non-null      float64
 11  month_code       0 non-null      int64
 12  county_code      0 non-null      int64
dtypes: float64(1), int64(8), object(4)
memory usage: 0.0+ bytes

In [737]:
malaria.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1692 entries, 0 to 1691
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       1692 non-null   int64
 1   period           1692 non-null   object
 2   year             1692 non-null   int64
 3   month            1692 non-null   object
 4   county           1692 non-null   object
 5   code             1692 non-null   object
 6   cases_under_5yo  1692 non-null   int64
 7   cases_over_5yo   1692 non-null   int64
 8   total_cases      1692 non-null   int64
 9   temp             1692 non-null   int64
 10  rainfall         1692 non-null   float64
 11  month_code       1692 non-null   int64
 12  county_code      1692 non-null   int64
dtypes: float64(1), int64(8), object(4)
memory usage: 172.0+ KB

In [738]:
malaria.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1692 entries, 0 to 1691
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       1692 non-null   int64
 1   period           1692 non-null   object
 2   year             1692 non-null   int64
 3   month            1692 non-null   object
 4   county           1692 non-null   object
 5   code             1692 non-null   object
 6   cases_under_5yo  1692 non-null   int64
 7   cases_over_5yo   1692 non-null   int64
 8   total_cases      1692 non-null   int64
 9   temp             1692 non-null   int64
 10  rainfall         1692 non-null   float64
 11  month_code       1692 non-null   int64
 12  county_code      1692 non-null   int64
dtypes: float64(1), int64(8), object(4)
memory usage: 172.0+ KB

In [739]:
missing_values = malaria[malaria.isnull().any(axis=1)]

In [740]:
missing_values

Empty DataFrame
Columns: [Unnamed: 0, period, year, month, county, code, cases_under_5yo, cases_over_5yo, total_cases, temp, rainfall, month_code, county_code]
Index: []

In [741]:
malaria.to_csv("../data/process_malaria.csv")

In [742]:
malaria.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1692 entries, 0 to 1691
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       1692 non-null   int64
 1   period           1692 non-null   object
 2   year             1692 non-null   int64
 3   month            1692 non-null   object
 4   county           1692 non-null   object
 5   code             1692 non-null   object
 6   cases_under_5yo  1692 non-null   int64
 7   cases_over_5yo   1692 non-null   int64
 8   total_cases      1692 non-null   int64
 9   temp             1692 non-null   int64
 10  rainfall         1692 non-null   float64
 11  month_code       1692 non-null   int64
 12  county_code      1692 non-null   int64
dtypes: float64(1), int64(8), object(4)
memory usage: 172.0+ KB

In [743]:
malaria.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1692 entries, 0 to 1691
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       1692 non-null   int64
 1   period           1692 non-null   object
 2   year             1692 non-null   int64
 3   month            1692 non-null   object
 4   county           1692 non-null   object
 5   code             1692 non-null   object
 6   cases_under_5yo  1692 non-null   int64
 7   cases_over_5yo   1692 non-null   int64
 8   total_cases      1692 non-null   int64
 9   temp             1692 non-null   int64
 10  rainfall         1692 non-null   float64
 11  month_code       1692 non-null   int64
 12  county_code      1692 non-null   int64
dtypes: float64(1), int64(8), object(4)
memory usage: 172.0+ KB

In [744]:
total_cases = malaria.groupby("county", as_index=False)["total_cases"].sum()

In [745]:
total_cases

             county  total_cases
0           Baringo       104975
1             Bomet         5509
2           Bungoma       879512
3             Busia       841629
4   Elgeyo Marakwet        32952
5              Embu         1989
6           Garissa         9699
7          Homa Bay       953684
8            Isiolo        12674
9           Kajiado        13928
10         Kakamega      1577695
11          Kericho       122226
12           Kiambu        13787
13           Kilifi       182466
14        Kirinyaga         1279
15            Kisii       170181
16           Kisumu      1148993
17            Kitui         1793
18            Kwale       290921
19         Laikipia         2799
20             Lamu          962
21         Machakos         8126
22          Makueni         2409
23          Mandera         7717
24         Marsabit         8272
25             Meru        11421
26           Migori      1606174
27          Mombasa        40296
28          Muranga         1399
29          Nairobi       103592
30           Nakuru        37525
31            Nandi       119819
32            Narok        38675
33          Nyamira        43841
34        Nyandarua          650
35            Nyeri         1239
36          Samburu        23853
37            Siaya      1821080
38     Taita Taveta         3040
39       Tana River        19219
40    Tharaka Nithi         5096
41      Trans Nzoia       183820
42          Turkana      1164073
43      Uasin Gishu        59694
44           Vihiga       395847
45            Wajir         2182
46       West Pokot       222224

In [746]:
max_cases = total_cases["total_cases"].max()

In [747]:
min_cases = total_cases["total_cases"].min()

In [748]:
max_cases

1821080

In [749]:
min_cases

650

In [750]:
max_county = total_cases[total_cases["total_cases"] == max_cases]["county"]

In [751]:
max_county

37    Siaya
Name: county, dtype: object

In [752]:
min_county = total_cases[total_cases["total_cases"] == min_cases]["county"]

In [753]:
min_county

34    Nyandarua
Name: county, dtype: object

In [754]:
siaya = malaria[malaria["county"] == "Siaya"].reset_index(drop=True)

In [755]:
siaya

,Unnamed: 0,period,year,month,county,code,cases_under_5yo,cases_over_5yo,total_cases,temp,rainfall,month_code,county_code
0,1332,22-Jan,2022,Jan,Siaya,KE_County_41,11708,46430,58138,24,16.76,1,41
1,1333,22-Feb,2022,Feb,Siaya,KE_County_41,10412,34007,44419,23,10.58,2,41
2,1334,22-Mar,2022,Mar,Siaya,KE_County_41,11858,31787,43645,25,163.97,3,41
3,1335,22-Apr,2022,Apr,Siaya,KE_County_41,9440,30100,39540,23,440.01,4,41
4,1336,22-May,2022,May,Siaya,KE_County_41,13424,46691,60115,22,282.81,5,41
5,1337,22-Jun,2022,Jun,Siaya,KE_County_41,17287,64885,82172,22,108.52,6,41
6,1338,22-Jul,2022,Jul,Siaya,KE_County_41,14934,53368,68302,22,156.43,7,41
7,1339,22-Aug,2022,Aug,Siaya,KE_County_41,11702,37523,49225,22,226.16,8,41
8,1340,22-Sep,2022,Sep,Siaya,KE_County_41,9589,30938,40527,22,227.00,9,41
9,1341,22-Oct,2022,Oct,Siaya,KE_County_41,10455,37473,47928,23,133.75,10,41
10,1342,22-Nov,2022,Nov,Siaya,KE_County_41,11844,36325,48169,22,94.40,11,41
11,1343,22-Dec,2022,Dec,Siaya,KE_County_41,9981,30159,40140,22,226.07,12,41
12,1344,23-Jan,2023,Jan,Siaya,KE_County_41,14520,42495,57015,24,123.04,1,41
13,1345,23-Feb,2023,Feb,Siaya,KE_County_41,11887,43852,55739,26,98.05,2,41
14,1346,23-Mar,2023,Mar,Siaya,KE_County_41,10296,38919,49215,23,408.35,3,41
15,1347,23-Apr,2023,Apr,Siaya,KE_County_41,11451,36112,47563,22,560.00,4,41
16,1348,23-May,2023,May,Siaya,KE_County_41,19078,76284,95362,22,207.40,5,41
17,1349,23-Jun,2023,Jun,Siaya,KE_County_41,17490,64492,81982,22,200.80,6,41
18,1350,23-Jul,2023,Jul,Siaya,KE_County_41,13248,48960,62208,23,103.80,7,41
19,1351,23-Aug,2023,Aug,Siaya,KE_County_41,13077,42261,55338,23,67.20,8,41
20,1352,23-Sep,2023,Sep,Siaya,KE_County_41,9918,41248,51166,22,237.08,9,41
21,1353,23-Oct,2023,Oct,Siaya,KE_County_41,9053,29227,38280,23,152.00,10,41
22,1354,23-Nov,2023,Nov,Siaya,KE_County_41,9316,27476,36792,22,422.30,11,41
23,1355,23-Dec,2023,Dec,Siaya,KE_County_41,8541,26714,35255,22,225.31,12,41
24,1356,24-Jan,2024,Jan,Siaya,KE_County_41,8974,31398,40372,22,35.74,1,41
25,1357,24-Feb,2024,Feb,Siaya,KE_County_41,9044,30147,39191,24,7.67,2,41
26,1358,24-Mar,2024,Mar,Siaya,KE_County_41,10863,40254,51117,24,93.83,3,41
27,1359,24-Apr,2024,Apr,Siaya,KE_County_41,7311,24664,31975,22,355.92,4,41
28,1360,24-May,2024,May,Siaya,KE_County_41,10443,42335,52778,21,336.58,5,41
29,1361,24-Jun,2024,Jun,Siaya,KE_County_41,12123,50217,62340,21,93.96,6,41
30,1362,24-Jul,2024,Jul,Siaya,KE_County_41,11586,43033,54619,22,74.08,7,41
31,1363,24-Aug,2024,Aug,Siaya,KE_County_41,10255,36878,47133,22,50.12,8,41
32,1364,24-Sep,2024,Sep,Siaya,KE_County_41,8892,38379,47271,23,85.06,9,41
33,1365,24-Oct,2024,Oct,Siaya,KE_County_41,7634,26600,34234,23,78.08,10,41
34,1366,24-Nov,2024,Nov,Siaya,KE_County_41,7525,25469,32994,22,301.97,11,41
35,1367,24-Dec,2024,Dec,Siaya,KE_County_41,8468,30353,38821,22,93.09,12,41

In [756]:
siaya.to_csv("../data/siaya.csv")

In [757]:
nyandarua = malaria[malaria["county"] == "Nyandarua"]

In [758]:
nyandarua

,Unnamed: 0,period,year,month,county,code,cases_under_5yo,cases_over_5yo,total_cases,temp,rainfall,month_code,county_code
1224,1224,22-Jan,2022,Jan,Nyandarua,KE_County_18,3,24,27,20,52.44,1,18
1225,1225,22-Feb,2022,Feb,Nyandarua,KE_County_18,0,14,14,22,22.20,2,18
1226,1226,22-Mar,2022,Mar,Nyandarua,KE_County_18,7,17,24,22,17.74,3,18
1227,1227,22-Apr,2022,Apr,Nyandarua,KE_County_18,3,18,21,20,129.90,4,18
1228,1228,22-May,2022,May,Nyandarua,KE_County_18,9,29,38,20,26.81,5,18
1229,1229,22-Jun,2022,Jun,Nyandarua,KE_County_18,5,14,19,18,13.00,6,18
1230,1230,22-Jul,2022,Jul,Nyandarua,KE_County_18,7,16,23,18,26.20,7,18
1231,1231,22-Aug,2022,Aug,Nyandarua,KE_County_18,6,14,20,18,36.36,8,18
1232,1232,22-Sep,2022,Sep,Nyandarua,KE_County_18,5,14,19,20,28.50,9,18
1233,1233,22-Oct,2022,Oct,Nyandarua,KE_County_18,3,12,15,21,13.30,10,18
1234,1234,22-Nov,2022,Nov,Nyandarua,KE_County_18,4,7,11,19,117.02,11,18
1235,1235,22-Dec,2022,Dec,Nyandarua,KE_County_18,1,10,11,19,29.44,12,18
1236,1236,23-Jan,2023,Jan,Nyandarua,KE_County_18,2,30,32,20,6.68,1,18
1237,1237,23-Feb,2023,Feb,Nyandarua,KE_County_18,6,22,28,22,0.24,2,18
1238,1238,23-Mar,2023,Mar,Nyandarua,KE_County_18,2,18,20,21,214.94,3,18
1239,1239,23-Apr,2023,Apr,Nyandarua,KE_County_18,9,11,20,19,208.50,4,18
1240,1240,23-May,2023,May,Nyandarua,KE_County_18,5,20,25,19,98.25,5,18
1241,1241,23-Jun,2023,Jun,Nyandarua,KE_County_18,3,16,19,19,46.45,6,18
1242,1242,23-Jul,2023,Jul,Nyandarua,KE_County_18,7,18,25,18,19.40,7,18
1243,1243,23-Aug,2023,Aug,Nyandarua,KE_County_18,2,14,16,19,23.20,8,18
1244,1244,23-Sep,2023,Sep,Nyandarua,KE_County_18,2,13,15,21,42.13,9,18
1245,1245,23-Oct,2023,Oct,Nyandarua,KE_County_18,1,5,6,21,36.35,10,18
1246,1246,23-Nov,2023,Nov,Nyandarua,KE_County_18,2,14,16,18,247.89,11,18
1247,1247,23-Dec,2023,Dec,Nyandarua,KE_County_18,4,10,14,19,80.69,12,18
1248,1248,24-Jan,2024,Jan,Nyandarua,KE_County_18,1,25,26,19,153.15,1,18
1249,1249,24-Feb,2024,Feb,Nyandarua,KE_County_18,2,8,10,21,59.89,2,18
1250,1250,24-Mar,2024,Mar,Nyandarua,KE_County_18,0,6,6,21,104.74,3,18
1251,1251,24-Apr,2024,Apr,Nyandarua,KE_County_18,0,16,16,19,490.56,4,18
1252,1252,24-May,2024,May,Nyandarua,KE_County_18,1,16,17,19,192.95,5,18
1253,1253,24-Jun,2024,Jun,Nyandarua,KE_County_18,3,5,8,18,67.43,6,18
1254,1254,24-Jul,2024,Jul,Nyandarua,KE_County_18,3,7,10,18,59.84,7,18
1255,1255,24-Aug,2024,Aug,Nyandarua,KE_County_18,2,32,34,19,6.11,8,18
1256,1256,24-Sep,2024,Sep,Nyandarua,KE_County_18,5,23,28,20,19.59,9,18
1257,1257,24-Oct,2024,Oct,Nyandarua,KE_County_18,2,2,4,22,0.09,10,18
1258,1258,24-Nov,2024,Nov,Nyandarua,KE_County_18,1,5,6,19,178.71,11,18
1259,1259,24-Dec,2024,Dec,Nyandarua,KE_County_18,1,6,7,19,38.00,12,18

In [759]:
nyandarua.to_csv("../data/nyandarua.csv")

In [760]:
nyandarua["temp"].mean()

np.float64(19.63888888888889)

In [761]:
nyandarua["rainfall"].mean()

np.float64(80.79694444444446)

In [762]:
max_cases = nyandarua["total_cases"].max()

In [763]:
max_cases

38

In [764]:
max_month = nyandarua[nyandarua["total_cases"] == max_cases]["period"]

In [765]:
max_month

1228    22-May
Name: period, dtype: object

In [766]:
nyandarua.loc[nyandarua["period"] == "May-22"]

Empty DataFrame
Columns: [Unnamed: 0, period, year, month, county, code, cases_under_5yo, cases_over_5yo, total_cases, temp, rainfall, month_code, county_code]
Index: []

In [767]:
max_rainfall = nyandarua["rainfall"].max()

In [768]:
max_rainfall

490.56

In [769]:
max_temp = nyandarua["temp"].max()

In [770]:
max_temp

22

In [771]:
siaya

,Unnamed: 0,period,year,month,county,code,cases_under_5yo,cases_over_5yo,total_cases,temp,rainfall,month_code,county_code
0,1332,22-Jan,2022,Jan,Siaya,KE_County_41,11708,46430,58138,24,16.76,1,41
1,1333,22-Feb,2022,Feb,Siaya,KE_County_41,10412,34007,44419,23,10.58,2,41
2,1334,22-Mar,2022,Mar,Siaya,KE_County_41,11858,31787,43645,25,163.97,3,41
3,1335,22-Apr,2022,Apr,Siaya,KE_County_41,9440,30100,39540,23,440.01,4,41
4,1336,22-May,2022,May,Siaya,KE_County_41,13424,46691,60115,22,282.81,5,41
5,1337,22-Jun,2022,Jun,Siaya,KE_County_41,17287,64885,82172,22,108.52,6,41
6,1338,22-Jul,2022,Jul,Siaya,KE_County_41,14934,53368,68302,22,156.43,7,41
7,1339,22-Aug,2022,Aug,Siaya,KE_County_41,11702,37523,49225,22,226.16,8,41
8,1340,22-Sep,2022,Sep,Siaya,KE_County_41,9589,30938,40527,22,227.00,9,41
9,1341,22-Oct,2022,Oct,Siaya,KE_County_41,10455,37473,47928,23,133.75,10,41
10,1342,22-Nov,2022,Nov,Siaya,KE_County_41,11844,36325,48169,22,94.40,11,41
11,1343,22-Dec,2022,Dec,Siaya,KE_County_41,9981,30159,40140,22,226.07,12,41
12,1344,23-Jan,2023,Jan,Siaya,KE_County_41,14520,42495,57015,24,123.04,1,41
13,1345,23-Feb,2023,Feb,Siaya,KE_County_41,11887,43852,55739,26,98.05,2,41
14,1346,23-Mar,2023,Mar,Siaya,KE_County_41,10296,38919,49215,23,408.35,3,41
15,1347,23-Apr,2023,Apr,Siaya,KE_County_41,11451,36112,47563,22,560.00,4,41
16,1348,23-May,2023,May,Siaya,KE_County_41,19078,76284,95362,22,207.40,5,41
17,1349,23-Jun,2023,Jun,Siaya,KE_County_41,17490,64492,81982,22,200.80,6,41
18,1350,23-Jul,2023,Jul,Siaya,KE_County_41,13248,48960,62208,23,103.80,7,41
19,1351,23-Aug,2023,Aug,Siaya,KE_County_41,13077,42261,55338,23,67.20,8,41
20,1352,23-Sep,2023,Sep,Siaya,KE_County_41,9918,41248,51166,22,237.08,9,41
21,1353,23-Oct,2023,Oct,Siaya,KE_County_41,9053,29227,38280,23,152.00,10,41
22,1354,23-Nov,2023,Nov,Siaya,KE_County_41,9316,27476,36792,22,422.30,11,41
23,1355,23-Dec,2023,Dec,Siaya,KE_County_41,8541,26714,35255,22,225.31,12,41
24,1356,24-Jan,2024,Jan,Siaya,KE_County_41,8974,31398,40372,22,35.74,1,41
25,1357,24-Feb,2024,Feb,Siaya,KE_County_41,9044,30147,39191,24,7.67,2,41
26,1358,24-Mar,2024,Mar,Siaya,KE_County_41,10863,40254,51117,24,93.83,3,41
27,1359,24-Apr,2024,Apr,Siaya,KE_County_41,7311,24664,31975,22,355.92,4,41
28,1360,24-May,2024,May,Siaya,KE_County_41,10443,42335,52778,21,336.58,5,41
29,1361,24-Jun,2024,Jun,Siaya,KE_County_41,12123,50217,62340,21,93.96,6,41
30,1362,24-Jul,2024,Jul,Siaya,KE_County_41,11586,43033,54619,22,74.08,7,41
31,1363,24-Aug,2024,Aug,Siaya,KE_County_41,10255,36878,47133,22,50.12,8,41
32,1364,24-Sep,2024,Sep,Siaya,KE_County_41,8892,38379,47271,23,85.06,9,41
33,1365,24-Oct,2024,Oct,Siaya,KE_County_41,7634,26600,34234,23,78.08,10,41
34,1366,24-Nov,2024,Nov,Siaya,KE_County_41,7525,25469,32994,22,301.97,11,41
35,1367,24-Dec,2024,Dec,Siaya,KE_County_41,8468,30353,38821,22,93.09,12,41

In [772]:
min_rainfall = siaya["rainfall"].mean()

In [773]:
min_rainfall

np.float64(180.49694444444447)

In [774]:
min_temp = siaya["temp"].mean()

In [775]:
min_temp

np.float64(22.61111111111111)

In [776]:
max_cases = siaya["total_cases"].max()

In [777]:
max_cases

95362

In [778]:
max_period = siaya[siaya["total_cases"] == max_cases]["period"]

In [779]:
max_period

16    23-May
Name: period, dtype: object

In [780]:
siaya.loc[siaya["period"] == "May-23"]

Empty DataFrame
Columns: [Unnamed: 0, period, year, month, county, code, cases_under_5yo, cases_over_5yo, total_cases, temp, rainfall, month_code, county_code]
Index: []

In [781]:
max_temp = siaya["temp"].max()

In [782]:
max_temp

26

In [783]:
max_rainfall = siaya["rainfall"].max()

In [784]:
max_rainfall

560.0

In [785]:
min_cases = siaya["total_cases"].min()

In [786]:
min_cases

31975

In [787]:
siaya.loc[siaya["total_cases"] == min_cases]

,Unnamed: 0,period,year,month,county,code,cases_under_5yo,cases_over_5yo,total_cases,temp,rainfall,month_code,county_code
27,1359,24-Apr,2024,Apr,Siaya,KE_County_41,7311,24664,31975,22,355.92,4,41

In [788]:
siaya.sort_values(by="total_cases", ascending=False)

,Unnamed: 0,period,year,month,county,code,cases_under_5yo,cases_over_5yo,total_cases,temp,rainfall,month_code,county_code
16,1348,23-May,2023,May,Siaya,KE_County_41,19078,76284,95362,22,207.40,5,41
5,1337,22-Jun,2022,Jun,Siaya,KE_County_41,17287,64885,82172,22,108.52,6,41
17,1349,23-Jun,2023,Jun,Siaya,KE_County_41,17490,64492,81982,22,200.80,6,41
6,1338,22-Jul,2022,Jul,Siaya,KE_County_41,14934,53368,68302,22,156.43,7,41
29,1361,24-Jun,2024,Jun,Siaya,KE_County_41,12123,50217,62340,21,93.96,6,41
18,1350,23-Jul,2023,Jul,Siaya,KE_County_41,13248,48960,62208,23,103.80,7,41
4,1336,22-May,2022,May,Siaya,KE_County_41,13424,46691,60115,22,282.81,5,41
0,1332,22-Jan,2022,Jan,Siaya,KE_County_41,11708,46430,58138,24,16.76,1,41
12,1344,23-Jan,2023,Jan,Siaya,KE_County_41,14520,42495,57015,24,123.04,1,41
13,1345,23-Feb,2023,Feb,Siaya,KE_County_41,11887,43852,55739,26,98.05,2,41
19,1351,23-Aug,2023,Aug,Siaya,KE_County_41,13077,42261,55338,23,67.20,8,41
30,1362,24-Jul,2024,Jul,Siaya,KE_County_41,11586,43033,54619,22,74.08,7,41
28,1360,24-May,2024,May,Siaya,KE_County_41,10443,42335,52778,21,336.58,5,41
20,1352,23-Sep,2023,Sep,Siaya,KE_County_41,9918,41248,51166,22,237.08,9,41
26,1358,24-Mar,2024,Mar,Siaya,KE_County_41,10863,40254,51117,24,93.83,3,41
7,1339,22-Aug,2022,Aug,Siaya,KE_County_41,11702,37523,49225,22,226.16,8,41
14,1346,23-Mar,2023,Mar,Siaya,KE_County_41,10296,38919,49215,23,408.35,3,41
10,1342,22-Nov,2022,Nov,Siaya,KE_County_41,11844,36325,48169,22,94.40,11,41
9,1341,22-Oct,2022,Oct,Siaya,KE_County_41,10455,37473,47928,23,133.75,10,41
15,1347,23-Apr,2023,Apr,Siaya,KE_County_41,11451,36112,47563,22,560.00,4,41
32,1364,24-Sep,2024,Sep,Siaya,KE_County_41,8892,38379,47271,23,85.06,9,41
31,1363,24-Aug,2024,Aug,Siaya,KE_County_41,10255,36878,47133,22,50.12,8,41
1,1333,22-Feb,2022,Feb,Siaya,KE_County_41,10412,34007,44419,23,10.58,2,41
2,1334,22-Mar,2022,Mar,Siaya,KE_County_41,11858,31787,43645,25,163.97,3,41
8,1340,22-Sep,2022,Sep,Siaya,KE_County_41,9589,30938,40527,22,227.00,9,41
24,1356,24-Jan,2024,Jan,Siaya,KE_County_41,8974,31398,40372,22,35.74,1,41
11,1343,22-Dec,2022,Dec,Siaya,KE_County_41,9981,30159,40140,22,226.07,12,41
3,1335,22-Apr,2022,Apr,Siaya,KE_County_41,9440,30100,39540,23,440.01,4,41
25,1357,24-Feb,2024,Feb,Siaya,KE_County_41,9044,30147,39191,24,7.67,2,41
35,1367,24-Dec,2024,Dec,Siaya,KE_County_41,8468,30353,38821,22,93.09,12,41
21,1353,23-Oct,2023,Oct,Siaya,KE_County_41,9053,29227,38280,23,152.00,10,41
22,1354,23-Nov,2023,Nov,Siaya,KE_County_41,9316,27476,36792,22,422.30,11,41
23,1355,23-Dec,2023,Dec,Siaya,KE_County_41,8541,26714,35255,22,225.31,12,41
33,1365,24-Oct,2024,Oct,Siaya,KE_County_41,7634,26600,34234,23,78.08,10,41
34,1366,24-Nov,2024,Nov,Siaya,KE_County_41,7525,25469,32994,22,301.97,11,41
27,1359,24-Apr,2024,Apr,Siaya,KE_County_41,7311,24664,31975,22,355.92,4,41

In [789]:
malaria

,Unnamed: 0,period,year,month,county,code,cases_under_5yo,cases_over_5yo,total_cases,temp,rainfall,month_code,county_code
0,0,22-Jan,2022,Jan,Baringo,KE_County_30,663,1975,2638,18,96.54,1,30
1,1,22-Feb,2022,Feb,Baringo,KE_County_30,805,1759,2564,19,45.28,2,30
2,2,22-Mar,2022,Mar,Baringo,KE_County_30,762,1370,2132,20,77.64,3,30
3,3,22-Apr,2022,Apr,Baringo,KE_County_30,597,1146,1743,19,261.67,4,30
4,4,22-May,2022,May,Baringo,KE_County_30,725,1700,2425,17,169.35,5,30
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1687,1687,24-Aug,2024,Aug,West Pokot,KE_County_24,2674,6152,8826,16,221.69,8,24
1688,1688,24-Sep,2024,Sep,West Pokot,KE_County_24,2018,4622,6640,17,172.77,9,24
1689,1689,24-Oct,2024,Oct,West Pokot,KE_County_24,1987,4859,6846,19,14.81,10,24
1690,1690,24-Nov,2024,Nov,West Pokot,KE_County_24,1992,4850,6842,18,154.62,11,24
1691,1691,24-Dec,2024,Dec,West Pokot,KE_County_24,1313,2335,3648,18,8.58,12,24

In [790]:
malaria.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1692 entries, 0 to 1691
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       1692 non-null   int64
 1   period           1692 non-null   object
 2   year             1692 non-null   int64
 3   month            1692 non-null   object
 4   county           1692 non-null   object
 5   code             1692 non-null   object
 6   cases_under_5yo  1692 non-null   int64
 7   cases_over_5yo   1692 non-null   int64
 8   total_cases      1692 non-null   int64
 9   temp             1692 non-null   int64
 10  rainfall         1692 non-null   float64
 11  month_code       1692 non-null   int64
 12  county_code      1692 non-null   int64
dtypes: float64(1), int64(8), object(4)
memory usage: 172.0+ KB

In [791]:
malaria["year"] = malaria["year"].astype(str).astype("period[Y]")

In [792]:
malaria.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1692 entries, 0 to 1691
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       1692 non-null   int64
 1   period           1692 non-null   object
 2   year             1692 non-null   period[Y-DEC]
 3   month            1692 non-null   object
 4   county           1692 non-null   object
 5   code             1692 non-null   object
 6   cases_under_5yo  1692 non-null   int64
 7   cases_over_5yo   1692 non-null   int64
 8   total_cases      1692 non-null   int64
 9   temp             1692 non-null   int64
 10  rainfall         1692 non-null   float64
 11  month_code       1692 non-null   int64
 12  county_code      1692 non-null   int64
dtypes: float64(1), int64(7), object(4), period[Y-DEC](1)
memory usage: 172.0+ KB

In [793]:
malaria

,Unnamed: 0,period,year,month,county,code,cases_under_5yo,cases_over_5yo,total_cases,temp,rainfall,month_code,county_code
0,0,22-Jan,2022,Jan,Baringo,KE_County_30,663,1975,2638,18,96.54,1,30
1,1,22-Feb,2022,Feb,Baringo,KE_County_30,805,1759,2564,19,45.28,2,30
2,2,22-Mar,2022,Mar,Baringo,KE_County_30,762,1370,2132,20,77.64,3,30
3,3,22-Apr,2022,Apr,Baringo,KE_County_30,597,1146,1743,19,261.67,4,30
4,4,22-May,2022,May,Baringo,KE_County_30,725,1700,2425,17,169.35,5,30
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1687,1687,24-Aug,2024,Aug,West Pokot,KE_County_24,2674,6152,8826,16,221.69,8,24
1688,1688,24-Sep,2024,Sep,West Pokot,KE_County_24,2018,4622,6640,17,172.77,9,24
1689,1689,24-Oct,2024,Oct,West Pokot,KE_County_24,1987,4859,6846,19,14.81,10,24
1690,1690,24-Nov,2024,Nov,West Pokot,KE_County_24,1992,4850,6842,18,154.62,11,24
1691,1691,24-Dec,2024,Dec,West Pokot,KE_County_24,1313,2335,3648,18,8.58,12,24

In [794]:
malaria["month_code"] = malaria["month"].apply(lambda x: {
    "January": 1, "February": 2, "March": 3, "April": 4,
    "May": 5, "June": 6, "July": 7, "August": 8,
    "September": 9, "October": 10, "November": 11, "December": 12,
    "Jan": 1, "Feb": 2, "Mar": 3, "Apr": 4,
    "Jun": 6, "Jul": 7, "Aug": 8, "Sep": 9,
    "Oct": 10, "Nov": 11, "Dec": 12
}.get(x.strip(), None))

In [795]:
malaria

,Unnamed: 0,period,year,month,county,code,cases_under_5yo,cases_over_5yo,total_cases,temp,rainfall,month_code,county_code
0,0,22-Jan,2022,Jan,Baringo,KE_County_30,663,1975,2638,18,96.54,1,30
1,1,22-Feb,2022,Feb,Baringo,KE_County_30,805,1759,2564,19,45.28,2,30
2,2,22-Mar,2022,Mar,Baringo,KE_County_30,762,1370,2132,20,77.64,3,30
3,3,22-Apr,2022,Apr,Baringo,KE_County_30,597,1146,1743,19,261.67,4,30
4,4,22-May,2022,May,Baringo,KE_County_30,725,1700,2425,17,169.35,5,30
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1687,1687,24-Aug,2024,Aug,West Pokot,KE_County_24,2674,6152,8826,16,221.69,8,24
1688,1688,24-Sep,2024,Sep,West Pokot,KE_County_24,2018,4622,6640,17,172.77,9,24
1689,1689,24-Oct,2024,Oct,West Pokot,KE_County_24,1987,4859,6846,19,14.81,10,24
1690,1690,24-Nov,2024,Nov,West Pokot,KE_County_24,1992,4850,6842,18,154.62,11,24
1691,1691,24-Dec,2024,Dec,West Pokot,KE_County_24,1313,2335,3648,18,8.58,12,24

In [796]:
malaria.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1692 entries, 0 to 1691
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       1692 non-null   int64
 1   period           1692 non-null   object
 2   year             1692 non-null   period[Y-DEC]
 3   month            1692 non-null   object
 4   county           1692 non-null   object
 5   code             1692 non-null   object
 6   cases_under_5yo  1692 non-null   int64
 7   cases_over_5yo   1692 non-null   int64
 8   total_cases      1692 non-null   int64
 9   temp             1692 non-null   int64
 10  rainfall         1692 non-null   float64
 11  month_code       1692 non-null   int64
 12  county_code      1692 non-null   int64
dtypes: float64(1), int64(7), object(4), period[Y-DEC](1)
memory usage: 172.0+ KB

In [797]:
malaria["county_code"] = malaria["code"].apply(lambda x: x.split("_")[-1])

In [798]:
malaria

,Unnamed: 0,period,year,month,county,code,cases_under_5yo,cases_over_5yo,total_cases,temp,rainfall,month_code,county_code
0,0,22-Jan,2022,Jan,Baringo,KE_County_30,663,1975,2638,18,96.54,1,30
1,1,22-Feb,2022,Feb,Baringo,KE_County_30,805,1759,2564,19,45.28,2,30
2,2,22-Mar,2022,Mar,Baringo,KE_County_30,762,1370,2132,20,77.64,3,30
3,3,22-Apr,2022,Apr,Baringo,KE_County_30,597,1146,1743,19,261.67,4,30
4,4,22-May,2022,May,Baringo,KE_County_30,725,1700,2425,17,169.35,5,30
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1687,1687,24-Aug,2024,Aug,West Pokot,KE_County_24,2674,6152,8826,16,221.69,8,24
1688,1688,24-Sep,2024,Sep,West Pokot,KE_County_24,2018,4622,6640,17,172.77,9,24
1689,1689,24-Oct,2024,Oct,West Pokot,KE_County_24,1987,4859,6846,19,14.81,10,24
1690,1690,24-Nov,2024,Nov,West Pokot,KE_County_24,1992,4850,6842,18,154.62,11,24
1691,1691,24-Dec,2024,Dec,West Pokot,KE_County_24,1313,2335,3648,18,8.58,12,24

In [799]:
malaria.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1692 entries, 0 to 1691
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       1692 non-null   int64
 1   period           1692 non-null   object
 2   year             1692 non-null   period[Y-DEC]
 3   month            1692 non-null   object
 4   county           1692 non-null   object
 5   code             1692 non-null   object
 6   cases_under_5yo  1692 non-null   int64
 7   cases_over_5yo   1692 non-null   int64
 8   total_cases      1692 non-null   int64
 9   temp             1692 non-null   int64
 10  rainfall         1692 non-null   float64
 11  month_code       1692 non-null   int64
 12  county_code      1692 non-null   object
dtypes: float64(1), int64(6), object(5), period[Y-DEC](1)
memory usage: 172.0+ KB

In [800]:
malaria["county_code"] = pd.to_numeric(malaria["county_code"])

In [801]:
malaria.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1692 entries, 0 to 1691
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       1692 non-null   int64
 1   period           1692 non-null   object
 2   year             1692 non-null   period[Y-DEC]
 3   month            1692 non-null   object
 4   county           1692 non-null   object
 5   code             1692 non-null   object
 6   cases_under_5yo  1692 non-null   int64
 7   cases_over_5yo   1692 non-null   int64
 8   total_cases      1692 non-null   int64
 9   temp             1692 non-null   int64
 10  rainfall         1692 non-null   float64
 11  month_code       1692 non-null   int64
 12  county_code      1692 non-null   int64
dtypes: float64(1), int64(7), object(4), period[Y-DEC](1)
memory usage: 172.0+ KB